if: (type = push AND branch IN(master,develop)) OR (type = pull_request AND NOT branch =~ /no-ci)
language : node_js
node_js
  - "stable"
notifications:
  email : false
before_script : 
  - npm install
script :
  - npm run test
after_script : 
  - npm run coverage
  - npm run coveralls
